const empresaMock = {
  id: 1,
  sigla: 'ABC',
  nome: 'Empresa ABC',
  ativo: true,
  dataCriacao: '2025-07-24T14:20:52.631Z',
  usuarioCriacao: 'admin',
  dataAlteracao: '2025-07-24T14:20:52.631Z',
  usuarioAlteracao: 'admin',
};

const usuarioBase = {
  id: 1,
  nome: 'João da Silva',
  email: 'joao@empresa.com',
  cargo: 'Analista',
  chaveAd: 'joao.silva',
  ativo: true,
  dataCriacao: '2025-07-24T14:20:52.632Z',
  usuarioCriacao: 'admin',
  dataAlteracao: '2025-07-24T14:20:52.632Z',
  usuarioAlteracao: 'admin',
  empresa: empresaMock,
  usuarioPerfis: [],
};

export const mockNotification = [
  {
    id: 1,
    descricao:
      'Usuário com uma descrição gigantesta do que deve ser feito aqui kkkkk',
    lido: false,
    dataCriacao: '2025-07-24T14:20:52.632Z',
    dataAlteracao: '2025-07-24T14:20:52.632Z',
    usuario: {
      ...usuarioBase,
      usuarioPerfis: [
        {
          id: 1,
          usuario: 'joao.silva',
          dataCriacao: '2025-07-24T14:20:52.632Z',
          usuarioCriacao: 'admin',
          perfil: {
            id: 1,
            desc: 'Administrador',
            ativo: true,
            dataCriacao: '2025-07-24T14:20:52.631Z',
            usuarioCriacao: 'admin',
            dataAlteracao: '2025-07-24T14:20:52.631Z',
            usuarioAlteracao: 'admin',
            usuarioPerfis: [],
            perfilMenus: [
              {
                id: 1,
                perfil: 'Administrador',
                descNivelAcesso: 'Total',
                dataCriacao: '2025-07-24T14:20:52.631Z',
                usuarioCriacao: 'admin',
                dataAlteracao: '2025-07-24T14:20:52.631Z',
                usuarioAlteracao: 'admin',
                menu: {
                  id: 1,
                  desc: 'Dashboard',
                  caminho: '/dashboard',
                  menuPrincipal: null,
                  ordemExibicao: 1,
                  dataCriacao: '2025-07-24T14:20:52.631Z',
                  usuarioCriacao: 'admin',
                  dataAlteracao: '2025-07-24T14:20:52.631Z',
                  usuarioAlteracao: 'admin',
                  perfilMenus: [],
                  sistema: {
                    id: 1,
                    sigla: 'SIS',
                    nome: 'Sistema de Gestão',
                    ativo: true,
                    dataCriacao: '2025-07-24T14:20:52.631Z',
                    usuarioCriacao: 'admin',
                    dataAlteracao: '2025-07-24T14:20:52.631Z',
                    usuarioAlteracao: 'admin',
                    empresa: empresaMock,
                  },
                },
              },
            ],
            sistema: {
              id: 1,
              sigla: 'SIS',
              nome: 'Sistema de Gestão',
              ativo: true,
              dataCriacao: '2025-07-24T14:20:52.631Z',
              usuarioCriacao: 'admin',
              dataAlteracao: '2025-07-24T14:20:52.631Z',
              usuarioAlteracao: 'admin',
              empresa: empresaMock,
            },
          },
        },
      ],
    },
    usuarioCriacao: usuarioBase,
    usuarioAlteracao: usuarioBase,
  },
  {
    id: 2,
    descricao: 'Notificação de teste',
    lido: false,
    dataCriacao: '2025-07-30T14:20:52.632Z',
    dataAlteracao: '2025-07-24T14:20:52.632Z',
    usuario: {
      ...usuarioBase,
      usuarioPerfis: [
        {
          id: 1,
          usuario: 'joao.silva',
          dataCriacao: '2025-07-24T14:20:52.632Z',
          usuarioCriacao: 'admin',
          perfil: {
            id: 1,
            desc: 'Administrador',
            ativo: true,
            dataCriacao: '2025-07-24T14:20:52.631Z',
            usuarioCriacao: 'admin',
            dataAlteracao: '2025-07-24T14:20:52.631Z',
            usuarioAlteracao: 'admin',
            usuarioPerfis: [],
            perfilMenus: [
              {
                id: 1,
                perfil: 'Administrador',
                descNivelAcesso: 'Total',
                dataCriacao: '2025-07-24T14:20:52.631Z',
                usuarioCriacao: 'admin',
                dataAlteracao: '2025-07-24T14:20:52.631Z',
                usuarioAlteracao: 'admin',
                menu: {
                  id: 1,
                  desc: 'Dashboard',
                  caminho: '/dashboard',
                  menuPrincipal: null,
                  ordemExibicao: 1,
                  dataCriacao: '2025-07-24T14:20:52.631Z',
                  usuarioCriacao: 'admin',
                  dataAlteracao: '2025-07-24T14:20:52.631Z',
                  usuarioAlteracao: 'admin',
                  perfilMenus: [],
                  sistema: {
                    id: 1,
                    sigla: 'SIS',
                    nome: 'Sistema de Gestão',
                    ativo: true,
                    dataCriacao: '2025-07-24T14:20:52.631Z',
                    usuarioCriacao: 'admin',
                    dataAlteracao: '2025-07-24T14:20:52.631Z',
                    usuarioAlteracao: 'admin',
                    empresa: empresaMock,
                  },
                },
              },
            ],
            sistema: {
              id: 1,
              sigla: 'SIS',
              nome: 'Sistema de Gestão',
              ativo: true,
              dataCriacao: '2025-07-24T14:20:52.631Z',
              usuarioCriacao: 'admin',
              dataAlteracao: '2025-07-24T14:20:52.631Z',
              usuarioAlteracao: 'admin',
              empresa: empresaMock,
            },
          },
        },
      ],
    },
    usuarioCriacao: usuarioBase,
    usuarioAlteracao: usuarioBase,
  },
  {
    id: 3,
    descricao: 'Notificação de teste',
    lido: false,
    dataCriacao: '2025-07-22T14:20:52.632Z',
    dataAlteracao: '2025-07-24T14:20:52.632Z',
    usuario: {
      ...usuarioBase,
      usuarioPerfis: [
        {
          id: 1,
          usuario: 'joao.silva',
          dataCriacao: '2025-07-24T14:20:52.632Z',
          usuarioCriacao: 'admin',
          perfil: {
            id: 1,
            desc: 'Administrador',
            ativo: true,
            dataCriacao: '2025-07-24T14:20:52.631Z',
            usuarioCriacao: 'admin',
            dataAlteracao: '2025-07-24T14:20:52.631Z',
            usuarioAlteracao: 'admin',
            usuarioPerfis: [],
            perfilMenus: [
              {
                id: 1,
                perfil: 'Administrador',
                descNivelAcesso: 'Total',
                dataCriacao: '2025-07-24T14:20:52.631Z',
                usuarioCriacao: 'admin',
                dataAlteracao: '2025-07-24T14:20:52.631Z',
                usuarioAlteracao: 'admin',
                menu: {
                  id: 1,
                  desc: 'Dashboard',
                  caminho: '/dashboard',
                  menuPrincipal: null,
                  ordemExibicao: 1,
                  dataCriacao: '2025-07-24T14:20:52.631Z',
                  usuarioCriacao: 'admin',
                  dataAlteracao: '2025-07-24T14:20:52.631Z',
                  usuarioAlteracao: 'admin',
                  perfilMenus: [],
                  sistema: {
                    id: 1,
                    sigla: 'SIS',
                    nome: 'Sistema de Gestão',
                    ativo: true,
                    dataCriacao: '2025-07-24T14:20:52.631Z',
                    usuarioCriacao: 'admin',
                    dataAlteracao: '2025-07-24T14:20:52.631Z',
                    usuarioAlteracao: 'admin',
                    empresa: empresaMock,
                  },
                },
              },
            ],
            sistema: {
              id: 1,
              sigla: 'SIS',
              nome: 'Sistema de Gestão',
              ativo: true,
              dataCriacao: '2025-07-24T14:20:52.631Z',
              usuarioCriacao: 'admin',
              dataAlteracao: '2025-07-24T14:20:52.631Z',
              usuarioAlteracao: 'admin',
              empresa: empresaMock,
            },
          },
        },
      ],
    },
    usuarioCriacao: usuarioBase,
    usuarioAlteracao: usuarioBase,
  },
  {
    id: 4,
    descricao: 'Notificação de teste',
    lido: false,
    dataCriacao: '2025-07-24T18:20:52.632Z',
    dataAlteracao: '2025-07-24T14:20:52.632Z',
    usuario: {
      ...usuarioBase,
      usuarioPerfis: [
        {
          id: 1,
          usuario: 'joao.silva',
          dataCriacao: '2025-07-24T14:20:52.632Z',
          usuarioCriacao: 'admin',
          perfil: {
            id: 1,
            desc: 'Administrador',
            ativo: true,
            dataCriacao: '2025-07-24T14:20:52.631Z',
            usuarioCriacao: 'admin',
            dataAlteracao: '2025-07-24T14:20:52.631Z',
            usuarioAlteracao: 'admin',
            usuarioPerfis: [],
            perfilMenus: [
              {
                id: 1,
                perfil: 'Administrador',
                descNivelAcesso: 'Total',
                dataCriacao: '2025-07-24T14:20:52.631Z',
                usuarioCriacao: 'admin',
                dataAlteracao: '2025-07-24T14:20:52.631Z',
                usuarioAlteracao: 'admin',
                menu: {
                  id: 1,
                  desc: 'Dashboard',
                  caminho: '/dashboard',
                  menuPrincipal: null,
                  ordemExibicao: 1,
                  dataCriacao: '2025-07-24T14:20:52.631Z',
                  usuarioCriacao: 'admin',
                  dataAlteracao: '2025-07-24T14:20:52.631Z',
                  usuarioAlteracao: 'admin',
                  perfilMenus: [],
                  sistema: {
                    id: 1,
                    sigla: 'SIS',
                    nome: 'Sistema de Gestão',
                    ativo: true,
                    dataCriacao: '2025-07-24T14:20:52.631Z',
                    usuarioCriacao: 'admin',
                    dataAlteracao: '2025-07-24T14:20:52.631Z',
                    usuarioAlteracao: 'admin',
                    empresa: empresaMock,
                  },
                },
              },
            ],
            sistema: {
              id: 1,
              sigla: 'SIS',
              nome: 'Sistema de Gestão',
              ativo: true,
              dataCriacao: '2025-07-24T14:20:52.631Z',
              usuarioCriacao: 'admin',
              dataAlteracao: '2025-07-24T14:20:52.631Z',
              usuarioAlteracao: 'admin',
              empresa: empresaMock,
            },
          },
        },
      ],
    },
    usuarioCriacao: usuarioBase,
    usuarioAlteracao: usuarioBase,
  },
  {
    id: 5,
    descricao: 'Notificação de teste',
    lido: false,
    dataCriacao: '2025-07-24T20:09:25.000Z',
    dataAlteracao: '2025-07-24T19:20:52.632Z',
    usuario: {
      ...usuarioBase,
      usuarioPerfis: [
        {
          id: 1,
          usuario: 'joao.silva',
          dataCriacao: '2025-07-24T14:20:52.632Z',
          usuarioCriacao: 'admin',
          perfil: {
            id: 1,
            desc: 'Administrador',
            ativo: true,
            dataCriacao: '2025-07-24T14:20:52.631Z',
            usuarioCriacao: 'admin',
            dataAlteracao: '2025-07-24T14:20:52.631Z',
            usuarioAlteracao: 'admin',
            usuarioPerfis: [],
            perfilMenus: [
              {
                id: 1,
                perfil: 'Administrador',
                descNivelAcesso: 'Total',
                dataCriacao: '2025-07-24T14:20:52.631Z',
                usuarioCriacao: 'admin',
                dataAlteracao: '2025-07-24T14:20:52.631Z',
                usuarioAlteracao: 'admin',
                menu: {
                  id: 1,
                  desc: 'Dashboard',
                  caminho: '/dashboard',
                  menuPrincipal: null,
                  ordemExibicao: 1,
                  dataCriacao: '2025-07-24T14:20:52.631Z',
                  usuarioCriacao: 'admin',
                  dataAlteracao: '2025-07-24T14:20:52.631Z',
                  usuarioAlteracao: 'admin',
                  perfilMenus: [],
                  sistema: {
                    id: 1,
                    sigla: 'SIS',
                    nome: 'Sistema de Gestão',
                    ativo: true,
                    dataCriacao: '2025-07-24T14:20:52.631Z',
                    usuarioCriacao: 'admin',
                    dataAlteracao: '2025-07-24T14:20:52.631Z',
                    usuarioAlteracao: 'admin',
                    empresa: empresaMock,
                  },
                },
              },
            ],
            sistema: {
              id: 1,
              sigla: 'SIS',
              nome: 'Sistema de Gestão',
              ativo: true,
              dataCriacao: '2025-07-24T14:20:52.631Z',
              usuarioCriacao: 'admin',
              dataAlteracao: '2025-07-24T14:20:52.631Z',
              usuarioAlteracao: 'admin',
              empresa: empresaMock,
            },
          },
        },
      ],
    },
    usuarioCriacao: usuarioBase,
    usuarioAlteracao: usuarioBase,
  },
];
